CREATE TABLE IF NOT EXISTS backtest_metrics (
    id                 BIGSERIAL PRIMARY KEY,
    run_id             UUID NOT NULL REFERENCES backtest_runs(id) ON DELETE CASCADE,
    total_return       NUMERIC(12,6),
    annualized_return  NUMERIC(12,6),
    benchmark_return   NUMERIC(12,6),
    alpha              NUMERIC(12,6),
    volatility         NUMERIC(12,6),
    max_drawdown       NUMERIC(12,6),
    max_drawdown_start DATE,
    max_drawdown_end   DATE,
    sharpe_ratio       NUMERIC(12,6),
    sortino_ratio      NUMERIC(12,6),
    calmar_ratio       NUMERIC(12,6),
    omega_ratio        NUMERIC(12,6),
    total_trades       INTEGER,
    winning_trades     INTEGER,
    losing_trades      INTEGER,
    win_rate           NUMERIC(8,6),
    avg_win_pct        NUMERIC(12,6),
    avg_loss_pct       NUMERIC(12,6),
    profit_factor      NUMERIC(12,6),
    avg_holding_days   NUMERIC(10,2),
    total_commission   NUMERIC(18,2),
    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (run_id)
);
